---

- src: ome.omero_common
- src: ome.basedeps
- name: java
  src: https://github.com/dominikl/ansible-role-java
  version: temurin
- src: ome.python3_virtualenv
- src: ome.ice
- src: ome.postgresql_client
